name: jaffle_shop_two
version: '0.1'
profile: jaffle_shop
config-version: 2
model-paths:
  - models
target-path: target
clean-targets:
  - target
  - dbt_modules
  - logs
models:
  jaffle_shop_two:
    +materialized: table
